baseurl = "/"
title = "SmartFootyFans"
theme = "casper3"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "My headline"
    description = "a Data Science x Aussie Rules Football project"
    github = "https://github.com/XXX"
    twitter = "https://twitter.com/XXX"
    email = "XXX@example.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"